package sjx.demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sjx.demo.bean.RoleDept;
import sjx.demo.bean.RoleDeptExample;

public interface RoleDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    long countByExample(RoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int deleteByExample(RoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int insert(RoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int insertSelective(RoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    List<RoleDept> selectByExample(RoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    RoleDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") RoleDept record, @Param("example") RoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByExample(@Param("record") RoleDept record, @Param("example") RoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(RoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByPrimaryKey(RoleDept record);
}