package sjx.demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sjx.demo.bean.SysConfig;
import sjx.demo.bean.SysConfigExample;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    long countByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int deleteByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String variable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int insertSelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    List<SysConfig> selectByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    SysConfig selectByPrimaryKey(String variable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") SysConfig record, @Param("example") SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByExample(@Param("record") SysConfig record, @Param("example") SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    int updateByPrimaryKey(SysConfig record);
}