package sjx.demo.bean;

import java.io.Serializable;
import java.util.Date;

public class SysConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.variable
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    private String variable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.value
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.set_time
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    private Date setTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.set_by
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    private String setBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.variable
     *
     * @return the value of sys_config.variable
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public String getVariable() {
        return variable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.variable
     *
     * @param variable the value for sys_config.variable
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public void setVariable(String variable) {
        this.variable = variable == null ? null : variable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.value
     *
     * @return the value of sys_config.value
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.value
     *
     * @param value the value for sys_config.value
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.set_time
     *
     * @return the value of sys_config.set_time
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public Date getSetTime() {
        return setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.set_time
     *
     * @param setTime the value for sys_config.set_time
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public void setSetTime(Date setTime) {
        this.setTime = setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.set_by
     *
     * @return the value of sys_config.set_by
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public String getSetBy() {
        return setBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.set_by
     *
     * @param setBy the value for sys_config.set_by
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    public void setSetBy(String setBy) {
        this.setBy = setBy == null ? null : setBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Sat Oct 31 09:45:15 GMT+08:00 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", variable=").append(variable);
        sb.append(", value=").append(value);
        sb.append(", setTime=").append(setTime);
        sb.append(", setBy=").append(setBy);
        sb.append("]");
        return sb.toString();
    }
}